import os
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor
from typing import List, Dict, Any, Union, Tuple

from axetract.utils.json_util import extract_and_repair_json, is_schema
from axetract.utils.html_util import find_closest_html_node, normalize_html_text
from axetract.data_types import AXESample, Status
from axetract.postprocessor.base_postprocessor import BasePostprocessor

# ==============================================================================
# WORKER FUNCTION (Top-level for Pickling)
# ==============================================================================

def _recursive_exact_extract(data: Any, content: str) -> Tuple[Any, Any]:
    """Recursively perform fuzzy matching on dictionaries and lists. Returns (values, xpaths)."""
    if isinstance(data, dict):
        result_vals = {}
        result_xpaths = {}
        for k, v in data.items():
            val, xp = _recursive_exact_extract(v, content)
            result_vals[k] = val
            result_xpaths[k] = xp
        return result_vals, result_xpaths
    elif isinstance(data, list):
        vals = []
        xpaths = []
        for item in data:
            val, xp = _recursive_exact_extract(item, content)
            vals.append(val)
            xpaths.append(xp)
        return vals, xpaths
    elif data is None:
        return None, None
    else:
        try:
            val_str = str(data)
            best_match = find_closest_html_node(html_text=content, search_text=val_str)
            
            val = normalize_html_text(best_match['text']) if best_match and 'text' in best_match else None
            xp = best_match['xpath'] if best_match and 'xpath' in best_match else None
            
            return val, xp
        except Exception as e:
            return {"__error__": f"[MATCH_ERROR] {e}", "original": data}, None


def _safe_extract_worker(response: str, content: str, query: Any, extract_exact: bool) -> Tuple[Union[Dict[str, Any], str], Optional[Dict[str, Any]]]:
    """
    Optimized worker that takes raw strings instead of a meta dict.
    Returns (parsed_response, xpaths).
    """
    try:
        if not response:
            return "", None

        # 1. Parse JSON
        # Determine if query is a schema or not
        if query is not None and not isinstance(query, str):
            # If it's a Pydantic model or other type, we treat it as a schema
            is_schema_query = True
        else:
            query_str = str(query) if query is not None else ""
            is_schema_query = is_schema(query_str) if query_str else False
            
        parsed_response = extract_and_repair_json(response, not is_schema_query)

        if isinstance(parsed_response, str):
            return parsed_response, None
            
        # Validate dict
        if not isinstance(parsed_response, dict):
            return {"__error__": "[PARSE_ERROR] expected JSON object (dict) from extract_and_repair_json"}, None
        
        # 2. Exact Extraction (Heavy CPU part)
        xpaths = None
        if extract_exact:
            if not content:
                return {"__error__": "[PARSE_ERROR] exact_extraction requested but no content provided"}, None

            parsed_response, xpaths = _recursive_exact_extract(parsed_response, content)

        return parsed_response, xpaths

    except Exception as e:
        return {"__error__": f"[PARSE_ERROR] {e}"}, None


# ==============================================================================
# CLASS DEFINITION
# ==============================================================================

class AXEPostProcessor(BasePostprocessor):
    """
    Optimized PostProcessor for high-throughput batch processing.
    """
    def __init__(self, name: str = "axe_postprocessor", exact_extraction: bool = False):
        super().__init__(name=name)
        self._exact_extraction = exact_extraction

    def __call__(self, samples: List[AXESample]) -> List[AXESample]:
        """
        Parallel processing core.
        """
        if not samples:
            return samples

        n_items = len(samples)
        # Leave one core free for system stability
        n_workers = max(1, (os.cpu_count() or 2) - 1)

        Executor = ProcessPoolExecutor if self._exact_extraction else ThreadPoolExecutor

        # Prepare flags generator
        extract_flags = [self._exact_extraction] * n_items

        # We assume sample.prediction holds the raw LLM string generated by the extractor
        responses = [s.prediction if isinstance(s.prediction, str) else str(s.prediction) for s in samples]
        queries = [s.query or s.schema_model for s in samples]
        
        # We perform exact_extraction matching using the current HTML processing output
        contents = [s.current_html for s in samples]

        # EXECUTE IN PARALLEL
        with Executor(max_workers=n_workers) as ex:
            parsed_results = list(ex.map(
                _safe_extract_worker, 
                responses, 
                contents, 
                queries, 
                extract_flags
            ))

        # Re-assemble results in the main process
        for sample, (parsed, xpaths) in zip(samples, parsed_results):
            sample.prediction = parsed
            sample.xpaths = xpaths
            
        return samples