from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional, Type, Union

from pydantic import BaseModel


class Status(Enum):
    """Execution status for a processing sample."""

    PENDING = "pending"
    SUCCESS = "success"
    FAILED = "failed"


class TokenUsage(BaseModel):
    """Real token usage reported by an LLM backend for one or more calls.

    Accumulated across a batch.  ``prompt_tokens`` are the tokens the model
    actually received (post-preprocessing / post-pruning), and
    ``completion_tokens`` are the tokens it generated.

    Attributes:
        prompt_tokens (int): Total input tokens seen by the model.
        completion_tokens (int): Total output tokens generated by the model.
    """

    prompt_tokens: int = 0
    completion_tokens: int = 0

    def add(self, prompt: int, completion: int) -> None:
        """Accumulate prompt/completion token counts."""
        self.prompt_tokens += int(prompt or 0)
        self.completion_tokens += int(completion or 0)

    def merge(self, other: "TokenUsage") -> None:
        """Merge another :class:`TokenUsage` into this one."""
        self.prompt_tokens += other.prompt_tokens
        self.completion_tokens += other.completion_tokens


class AXEChunk(BaseModel):
    """A single chunk of HTML content.

    Attributes:
        chunkid (str): Unique identifier for the chunk.
        content (str): The raw or cleaned HTML content.
    """

    chunkid: str
    content: str


class AXESample(BaseModel):
    """A data container for a single extraction request throughout the pipeline.

    Attributes:
        id (str): Unique identifier for the sample.
        content (str): Input content (URL or raw HTML).
        is_content_url (bool): Whether the content is a URL.
        query (Optional[str]): Natural language extraction query.
        schema_model (Optional[Union[str, Type[BaseModel], dict]]): Desired JSON schema.
        chunks (List[AXEChunk]): List of processed HTML chunks.
        original_html (str): The original, uncleaned HTML content.
        current_html (str): The current state of HTML (e.g., after cleaning or pruning).
        prediction (Optional[Union[str, dict, Any]]): The LLM's raw output or
            parsed JSON.  Overwritten by the postprocessor with the parsed
            structured result.
        raw_prediction (Optional[Union[str, Any]]): The raw LLM completion as
            returned by the extractor, preserved across postprocessing so
            benchmarking can measure true LLM output size.
        xpaths (Optional[dict]): Map of extracted fields to their source XPaths.
        status (Status): Current processing status.
    """

    id: str
    content: str
    is_content_url: bool
    query: Optional[str] = None
    schema_model: Optional[Union[str, Type[BaseModel], dict]] = None
    chunks: List[AXEChunk] = []
    original_html: str = ""
    current_html: str = ""
    prediction: Optional[Union[str, dict, Any]] = None
    raw_prediction: Optional[Union[str, Any]] = None
    xpaths: Optional[dict] = None

    status: Status = Status.PENDING

    # ── Real token usage (populated by pruner / extractor) ──
    # ``pruner_usage`` accumulates tokens consumed by the chunk-level pruner
    # LLM calls; ``extractor_usage`` accumulates tokens consumed by the
    # final extraction LLM call.  Both are :class:`TokenUsage` instances so
    # the benchmark can report true LLM input/output token counts (as opposed
    # to the char/4 heuristic over raw HTML).
    pruner_usage: TokenUsage = TokenUsage()
    extractor_usage: TokenUsage = TokenUsage()


class AXEResult(BaseModel):
    """Final extraction result returned to the user.

    Attributes:
        id (str): Sample identifier.
        prediction (Union[str, dict, Any]): The extracted structured data.
        xpaths (Optional[dict]): Reference XPaths for the extracted values.
        status (Status): Success or failure indicator.
        error (Optional[str]): Error message if processing failed.
        raw_prediction (Optional[Union[str, Any]]): The raw LLM completion as
            returned by the extractor, preserved across postprocessing so
            benchmarking can measure true LLM output size.
        pruner_usage (TokenUsage): Real token usage from the pruner LLM calls.
        extractor_usage (TokenUsage): Real token usage from the extractor LLM call.
    """

    id: str
    prediction: Union[str, dict, Any]
    xpaths: Optional[dict] = None
    status: Status
    error: Optional[str] = None
    raw_prediction: Optional[Union[str, Any]] = None
    pruner_usage: TokenUsage = TokenUsage()
    extractor_usage: TokenUsage = TokenUsage()
